/**
 * Codes d'erreur métier stables, exposés dans l'enveloppe d'erreur JSON.
 * Le frontend peut s'appuyer sur ces codes (pas sur les messages).
 */
export enum ErrorCode {
  // Générique
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',

  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',

  // Autorisation vendeur
  SELLER_NOT_APPROVED = 'SELLER_NOT_APPROVED',
  SELLER_ALREADY_EXISTS = 'SELLER_ALREADY_EXISTS',
  SELLER_APPLICATION_PENDING = 'SELLER_APPLICATION_PENDING',
  NOT_SELLER = 'NOT_SELLER',

  // Catalogue
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_CONFLICT = 'CATEGORY_SLUG_CONFLICT',
  CATEGORY_IN_USE = 'CATEGORY_IN_USE',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_CONFLICT = 'PRODUCT_SLUG_CONFLICT',
  PRODUCT_NOT_OWNED = 'PRODUCT_NOT_OWNED',
  PRODUCT_NOT_PUBLISHED = 'PRODUCT_NOT_PUBLISHED',

  // Panier
  CART_EMPTY = 'CART_EMPTY',
  CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',

  // Commandes
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_NOT_OWNED = 'ORDER_NOT_OWNED',
  ORDER_INVALID_TRANSITION = 'ORDER_INVALID_TRANSITION',
  ORDER_NOT_CANCELLABLE = 'ORDER_NOT_CANCELLABLE',
  DUPLICATE_ORDER = 'DUPLICATE_ORDER',

  // Paiements
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_VERIFIED = 'PAYMENT_ALREADY_VERIFIED',
  PAYMENT_REFERENCE_USED = 'PAYMENT_REFERENCE_USED',
  PAYMENT_NOT_SUBMITTED = 'PAYMENT_NOT_SUBMITTED',
  PAYMENT_AMOUNT_MISMATCH = 'PAYMENT_AMOUNT_MISMATCH',
  UNSUPPORTED_PROVIDER = 'UNSUPPORTED_PROVIDER',
}
