import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#fff8f3",
        "on-background": "#1d1b18",
        surface: "#fff8f3",
        "on-surface": "#1d1b18",
        "on-surface-variant": "#4a463f",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f2ed",
        "surface-container": "#f3ede8",
        "surface-container-high": "#ede7e2",
        "surface-container-highest": "#e8e1dc",
        "surface-dim": "#dfd9d4",
        "surface-bright": "#fff8f3",
        "surface-variant": "#e8e1dc",
        primary: "#272520",
        "on-primary": "#ffffff",
        "primary-container": "#3d3a35",
        "on-primary-container": "#a9a49d",
        "primary-fixed": "#e8e1da",
        "primary-fixed-dim": "#cbc6bf",
        secondary: "#735a3a",
        "on-secondary": "#ffffff",
        "secondary-container": "#fddab2",
        "on-secondary-container": "#785e3e",
        "secondary-fixed": "#ffddb6",
        "secondary-fixed-dim": "#e2c19b",
        tertiary: "#252522",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3a3b38",
        outline: "#7b766e",
        "outline-variant": "#ccc6bc",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        display: ["Libre Caslon Text", "Georgia", "serif"],
        body: ["Hanken Grotesk", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["72px", { lineHeight: "1.05", letterSpacing: "-0.02em" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        "display-md": ["40px", { lineHeight: "1.15", letterSpacing: "-0.01em" }],
        "headline-lg": ["36px", { lineHeight: "1.25" }],
        "headline-md": ["30px", { lineHeight: "1.3" }],
        "headline-sm": ["22px", { lineHeight: "1.4" }],
        "body-lg": ["18px", { lineHeight: "1.65" }],
        "body-md": ["16px", { lineHeight: "1.6" }],
        "body-sm": ["14px", { lineHeight: "1.6" }],
        "label-lg": ["15px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "500" }],
      },
      boxShadow: {
        card: "0 2px 12px rgba(29,27,24,0.06)",
        "card-hover": "0 20px 40px rgba(29,27,24,0.10)",
        drawer: "-10px 0 40px rgba(29,27,24,0.12)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96) translateY(8px)" },
          to: { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        "slide-left": { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-down": {
          from: { opacity: "0", transform: "translateY(-12px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "toast-in": {
          from: { opacity: "0", transform: "translateY(16px) scale(0.97)" },
          to: { opacity: "1", transform: "translateY(0) scale(1)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.25s ease-out",
        "scale-in": "scale-in 0.25s cubic-bezier(0.16,1,0.3,1)",
        "slide-left": "slide-left 0.35s cubic-bezier(0.16,1,0.3,1)",
        "slide-down": "slide-down 0.25s ease-out",
        "toast-in": "toast-in 0.3s cubic-bezier(0.16,1,0.3,1)",
      },
    },
  },
  plugins: [],
} satisfies Config;
